/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as NotesImport } from './routes/notes'
import { Route as NotesEditIdImport } from './routes/notes/edit/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const NotesEditIndexLazyImport = createFileRoute('/notes/edit/')()
const NotesCreateIndexLazyImport = createFileRoute('/notes/create/')()
const NotesCreateIdLazyImport = createFileRoute('/notes/create/$id')()

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const NotesRoute = NotesImport.update({
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NotesEditIndexLazyRoute = NotesEditIndexLazyImport.update({
  path: '/edit/',
  getParentRoute: () => NotesRoute,
} as any).lazy(() =>
  import('./routes/notes/edit/index.lazy').then((d) => d.Route),
)

const NotesCreateIndexLazyRoute = NotesCreateIndexLazyImport.update({
  path: '/create/',
  getParentRoute: () => NotesRoute,
} as any).lazy(() =>
  import('./routes/notes/create/index.lazy').then((d) => d.Route),
)

const NotesCreateIdLazyRoute = NotesCreateIdLazyImport.update({
  path: '/create/$id',
  getParentRoute: () => NotesRoute,
} as any).lazy(() =>
  import('./routes/notes/create/$id.lazy').then((d) => d.Route),
)

const NotesEditIdRoute = NotesEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => NotesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/notes/edit/$id': {
      id: '/notes/edit/$id'
      path: '/edit/$id'
      fullPath: '/notes/edit/$id'
      preLoaderRoute: typeof NotesEditIdImport
      parentRoute: typeof NotesImport
    }
    '/notes/create/$id': {
      id: '/notes/create/$id'
      path: '/create/$id'
      fullPath: '/notes/create/$id'
      preLoaderRoute: typeof NotesCreateIdLazyImport
      parentRoute: typeof NotesImport
    }
    '/notes/create/': {
      id: '/notes/create/'
      path: '/create'
      fullPath: '/notes/create'
      preLoaderRoute: typeof NotesCreateIndexLazyImport
      parentRoute: typeof NotesImport
    }
    '/notes/edit/': {
      id: '/notes/edit/'
      path: '/edit'
      fullPath: '/notes/edit'
      preLoaderRoute: typeof NotesEditIndexLazyImport
      parentRoute: typeof NotesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  NotesRoute: NotesRoute.addChildren({
    NotesEditIdRoute,
    NotesCreateIdLazyRoute,
    NotesCreateIndexLazyRoute,
    NotesEditIndexLazyRoute,
  }),
  SettingsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notes",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx",
      "children": [
        "/notes/edit/$id",
        "/notes/create/$id",
        "/notes/create/",
        "/notes/edit/"
      ]
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/notes/edit/$id": {
      "filePath": "notes/edit/$id.tsx",
      "parent": "/notes"
    },
    "/notes/create/$id": {
      "filePath": "notes/create/$id.lazy.tsx",
      "parent": "/notes"
    },
    "/notes/create/": {
      "filePath": "notes/create/index.lazy.tsx",
      "parent": "/notes"
    },
    "/notes/edit/": {
      "filePath": "notes/edit/index.lazy.tsx",
      "parent": "/notes"
    }
  }
}
ROUTE_MANIFEST_END */
